from __future__ import annotations
# pyright: reportMissingImports=false

from datetime import datetime, timezone
from html import escape
from pathlib import Path

from app.config import Settings


def render_estimate_screenshot(
    settings: Settings,
    provider: str,
    low_estimate: float,
    high_estimate: float,
    ride_type: str,
) -> str | None:
    try:
        from playwright.sync_api import sync_playwright
    except Exception:
        return None

    debug_dir = settings.scraper_debug_dir
    debug_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    file_name = f"{provider}_estimate_{timestamp}.png"
    target_path = debug_dir / file_name

    now_text = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    html = f"""
    <!doctype html>
    <html>
      <head>
        <style>
          body {{
            margin: 0;
            font-family: Segoe UI, Arial, sans-serif;
            background: linear-gradient(135deg, #f5f7fb, #e9eef8);
            color: #192231;
          }}
          .card {{
            width: 980px;
            height: 560px;
            box-sizing: border-box;
            padding: 40px;
            border: 1px solid #d8dfeb;
            border-radius: 22px;
            margin: 20px;
            background: #ffffff;
          }}
          h1 {{ margin: 0 0 8px 0; font-size: 40px; }}
          .meta {{ color: #5c6d84; font-size: 22px; margin-bottom: 24px; }}
          .price {{ color: #0c7d69; font-size: 58px; font-weight: 700; margin: 20px 0; }}
          .line {{ margin: 10px 0; font-size: 24px; }}
          .foot {{ margin-top: 26px; font-size: 18px; color: #5c6d84; }}
        </style>
      </head>
      <body>
        <div class='card'>
          <h1>{escape(provider.upper())} Price Snapshot</h1>
          <div class='meta'>Generated by tracker fallback estimate</div>
          <div class='price'>${low_estimate:.2f} - ${high_estimate:.2f}</div>
          <div class='line'><strong>Ride Type:</strong> {escape(ride_type)}</div>
          <div class='line'><strong>Route:</strong> {escape(settings.source_address)} -> {escape(settings.destination_address)}</div>
          <div class='line'><strong>Trip Date:</strong> {escape(settings.target_datetime)}</div>
          <div class='line'><strong>Passengers:</strong> {settings.passengers}</div>
          <div class='foot'>Captured at {escape(now_text)}</div>
        </div>
      </body>
    </html>
    """

    try:
        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(headless=True)
            page = browser.new_page(viewport={"width": 1040, "height": 620})
            page.set_content(html, wait_until="load")
            page.screenshot(path=str(target_path), full_page=True)
            browser.close()
        return file_name
    except Exception:
        return None
